---
- name: "Autodiscover: Init facts"
  set_fact:
    tmp_bb_services_pids: {}
    bb_service_ports: {}

- name: "Autodiscover: Get gridinit service PIDs"
  shell: "gridinit_cmd status @{{item}} | grep -v PID | awk '{print $3;}'"
  register: tmp_pids
  with_items: "{{ prometheus_blackbox_services }}"
  changed_when: false

- name: "Autodiscover: Format gridinit service PIDs"
  set_fact:
    tmp_bb_services_pids: "{{ tmp_bb_services_pids | combine({item.item: item.stdout_lines}) }}"
  with_items: "{{ tmp_pids['results'] }}"

- name: "Autodiscover: Get associated ports"
  shell: "netstat -lntp | grep '{{ item.1 | join('\\|') }}' | awk '{print $4;}' | sed -e 's/.*://';"
  register: tmp_bb_ports
  with_items:
    - "{{ tmp_bb_services_pids | dictsort }}"
  changed_when: false

- name: "Autodiscover: Format service ports"
  set_fact:
    bb_service_ports: "{{ bb_service_ports | combine({item.item.0: item.stdout_lines}) }}"
  with_items: "{{ tmp_bb_ports['results'] }}"
...
