---
- name: "Perform service autodiscovery"
  include: "autodiscovery.yml"
  when: prometheus_blackbox_group in group_names

- name: "Generate blackbox targets"
  template:
    src: blackbox.yml.j2
    dest: "{{ prometheus_conf_dir }}/targets/blackbox.yml"
  when: prometheus_admin_group in group_names
...
