---

- name: "Scan node service ports - {{item}}"
  command: "gridinit_cmd status @{{item}} | {{prometheus_blackbox_port_scan}}"
  register: bb_services
  with_items: "{{prometheus_blackbox_services}}"

- name: "Scan node service ports - all"
  command: "gridinit_cmd status | {{prometheus_blackbox_port_scan}}"
  register: bb_services_tcpcheck

- name: "Register fact: service ports"
  set_fact:
    prometheus_bb_services: "{{bb_services.stdout}}"

- name: "Register fact: service ports"
  set_fact:
    prometheus_bb_services: "{{bb_services_tcpcheck.stdout}}"

- name: "Create blackbox targets directory"
  file:
    path: "{{ prometheus_conf_dir }}/targets/blackbox"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755

- name: "Generate blackbox targets"
  template:
    src: blackbox_targets.yml.j2
    dest: "{{ prometheus_conf_dir }}/targets/blackbox/openio.yml"
...
