---
- block:
    - name: Perform checks
      include: preflight.yml

    - name: Prometheus > install
      include: "install/{{ ansible_distribution }}.yml"

    - name: Prometheus > configure
      include: "configure.yml"
      notify: reload prometheus

    # CONFIGURATION - PROMETHEUS

    - name: "Ensure prometheus is started/enabled"
      systemd:
        state: started
        daemon_reload: true
        enabled: true
        name: "prometheus"

    - name: "Wait until service is up"
      wait_for:
        host: "{{ prometheus_listen_ip }}"
        port: "{{ prometheus_listen_port }}"
        delay: 10
  when: prometheus_admin_group in group_names

- block:
    - name: "Blackbox > Perform service autodiscovery"
      include: "autodiscovery.yml"
      when: prometheus_blackbox_group in group_names

    - name: "Blackbox > Generate blackbox targets"
      template:
        src: blackbox.yml.j2
        dest: "{{ prometheus_conf_dir }}/targets/blackbox.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      when: prometheus_admin_group in group_names
      notify: reload prometheus
  when: prometheus_blackbox_enabled and bb_service_ports is defined

- name: "Netdata > configure"
  template:
    src: netdata.yml.j2
    dest: "{{ prometheus_conf_dir }}/targets/netdata.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  when: prometheus_netdata_enabled
  notify: reload prometheus
...
