---
- block:
    - name: Perform checks
      include: preflight.yml

    - name: Prometheus > install
      include: "install/{{ ansible_distribution }}.yml"

    - name: Prometheus > configure
      include: "configure.yml"
      notify: reload prometheus

    # CONFIGURATION - PROMETHEUS

    - name: "Ensure prometheus is started/enabled"
      systemd:
        state: started
        daemon_reload: true
        enabled: true
        name: "prometheus"

    - name: "Wait until service is up"
      wait_for:
        host: "{{ prometheus_listen_ip }}"
        port: "{{ prometheus_listen_port }}"
        delay: 10
  when: prometheus_admin_group in group_names

- name: Blackbox > configure
  include: "blackbox.yml"
  notify: reload prometheus
  when: prometheus_blackbox_enabled and prometheus_blackbox_group in group_names
...
