---
# handlers file for ansible-role-prometheus

- name: restart prometheus
  systemd:
    state: restarted
    daemon_reload: true
    name: prometheus

- name: reload prometheus
  systemd:
    state: reloaded
    name: prometheus
    daemon_reload: true

- name: stop prometheus
  systemd:
    state: stopped
    name: prometheus
    daemon_reload: true


- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true

- name: reload node_exporter
  systemd:
    name: node_exporter
    state: reloaded
    daemon_reload: true

- name: stop node_exporter
  systemd:
    name: node_exporter
    state: stopped
    daemon_reload: true

- name: restart alertmanager
  systemd:
    name: alertmanager
    state: restarted
    daemon_reload: true

- name: reload alertmanager
  systemd:
    name: alertmanager
    state: reloaded
    daemon_reload: true

- name: stop alertmanager
  systemd:
    name: alertmanager
    state: stopped
    daemon_reload: true
...
