---
# handlers file for ansible-role-prometheus

- name: restart prometheus
  systemd:
    state: restarted
    daemon_reload: true
    name: prometheus

- name: reload prometheus
  systemd:
    state: reloaded
    name: prometheus
    daemon_reload: true

- name: stop prometheus
  systemd:
    state: stopped
    name: prometheus
    daemon_reload: true
...
